# Generated by Django 3.2.12 on 2022-02-06 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo electrónico')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bank_account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=255, verbose_name='Número de cuenta')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo de cuenta')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta de Banco',
                'verbose_name_plural': 'Cuentas de Banco',
            },
        ),
    ]
