# Generated by Django 3.2.12 on 2022-02-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank_account',
        ),
    ]
